language: ruby
rvm:
- 2.0.0
before_script:
- npm install bower
- bower install
script: bundle exec middleman build
after_script: bundle exec middleman s3_sync --force
env:
  secure: dkT3atT9G1zFjlTwxkK9ymYJ9cf3BjsiuBa8URGtCeXzwCJ8M4pjDfT/0PxjLSrD8oYm6riM757TFdwcsCoGn46fZkWHgJnP+3AODMh/iwTeNLE3QoIEFhW4Oljyz8ogUQfjNsmNu5ev6cixcEZVa+IFchsq4lgTKaG8j+h6LHs=
