language: ruby
rvm:
- 2.0.0
before_script:
- npm install bower
- bower install
script: bundle exec middleman build
after_script: bundle exec middleman s3_sync --force
env:
  secure: FZkmjo9hddC4pi0Ct0td7pN7YM0LjGaTJ4yCnBX74Asl6ats9Lj/tymxJ3BRl9CXNtoeNCspLMLjj5N3KUGGwcxHvULbfKzPhPY5sNM792pN3qvyslRqNR4GAVZ5emdQJfLAngXWbgKv9K+A+JOgjbMUqOcYND9GG7zP1QQMyJA=
